version: "3.9"
services:
  mongo:
    image: mongo:6
    ports: ["27017:27017"]
    volumes: [ "mongo:/data/db" ]

  api:
    build: ./server
    environment:
      - MONGO_URL=mongodb://mongo:27017/daipay
      - PORT=8080
      - MAIL_USER=support@aiclone.me
      - MAIL_PASS=Puneri2
      - JWT_SECRET=harshpatel
      - APP_SECRET=B4SaCTNgthWQwfWXsogPP1TkoGWFDjUbizaQMSrUypyZ
    depends_on: [mongo]
    ports: ["8080:8080"]

  web:
    build: ./web
    environment:
      - VITE_API_BASE=http://localhost:8080/v1
      - VITE_APP_SECRET_KEY=H8mE2PtEmvBknpWk6p62qWajFAuB7tE2nZ7c9NcFZDe1
      - VITE_APP_SECRET=B4SaCTNgthWQwfWXsogPP1TkoGWFDjUbizaQMSrUypyZ
    depends_on: [api]
    ports: ["5173:5173"]

volumes:
  mongo: {}
